### PR TITLE
points dependencies to new locations

### PR DESCRIPTION
**Pull request by Thermatix**
Just updating the dependencies so they point to new locations as AWS has changed where they're stored.

### CODE REVIEW

**Comment by nmcclain** [comment]
Thermatix - thanks for this.  Unfortunately, the API for aws-sdk-go has changed, so most of the AWS code in traildash will need to be updated.  I'll try to tackle this in the coming weeks, or would gratefully accept a PR.

./traildash.go:291: too many arguments in call to sqs.New
./traildash.go:293: undefined: sqs.ReceiveMessageRequest
./traildash.go:336: too many arguments in call to s3.New
./traildash.go:337: undefined: s3.GetObjectRequest
./traildash.go:390: too many arguments in call to sqs.New
./traildash.go:391: undefined: sqs.DeleteMessageRequest
./traildash.go:395: multiple-value q.DeleteMessage() in single-value context

**Comment by nmcclain** [comment]
Merged this and updated for AWS SDK changes.

**Comment by Thermatix** [comment]
ah cool, truth is I realised this after I tried it with the changes but I never got around to pointing it out >_<. I'll be honest though I don't really know go, I only made some slight changes to locations, beyond that I wouldn't know what to do.

**Comment by nmcclain** [comment]
Good news - I got it taken care of and it has been merged to master.  Thanks for identifying this issue!

**Comment by Thermatix** [comment]
Thanks SUPER much!

**Pull request closed without merging**
